repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^templates/
      - id: end-of-file-fixer
        exclude: ^templates/
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: npm-verify
        name: npm verify
        entry: npm run verify
        language: system
        pass_filenames: false
